name = "frei konfigurierbare Falldaten"
description = "Einfaches, frei konfigurierbares Falldatenblatt mit verschiedenen Oberflächenelementen"
version = "0.4.0"
author = "Jens Kutschke"
updated = "04.09.2026"
