name = "frei konfigurierbare Falldaten"
description = "Einfaches, frei konfigurierbares Falldatenblatt mit verschiedenen Oberflächenelementen"
version = "0.3.0"
author = "Jens Kutschke"
updated = "02.04.2026"
